% move bvec and bval files to corected bvec and bval folders 
movefile('/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posC/OUTPUTS_future_fieldmap/bvec*', ...
    '/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posC/OUTPUTS_future_fieldmap/corrected_bvec');
movefile('/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posC/OUTPUTS_future_fieldmap/bval*', ...
    '/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posC/OUTPUTS_future_fieldmap/corrected_bval')