addpath(genpath('../external/spm_read_nii'))
addpath(genpath('../external/spm_reslice'))
addpath('sh_basis')

if 0
	fieldmaps_to_gradtensor( ...
		'fieldmap_hz_0_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_0_Hz.nii', ...
		'fieldmap_hz_x_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_X_Hz.nii', ...
		'fieldmap_hz_y_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_Y_Hz.nii', ...
		'fieldmap_hz_z_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_Z_Hz.nii', ...
		'sh_order',7, ...
		'symmetry','sym', ...
		'coord_geom','Philips_headfirst_supine', ...
		'image_radius',135, ...
		'out_dir','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/OUTPUTS' ...
		);
end


%create output dir
apply_gradtensor_to_b( ...	
    'Limg_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/OUTPUTS/L.nii.gz',   ...
    'refimg_file','/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posB/INPUTS/dwmri.nii.gz', ...	
    'bval_file','/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posB/INPUTS/dwmri.bval', ...
	'bvec_file','/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posB/INPUTS/dwmri.bvec', ...
	'out_dir','/nfs/masi/kanakap/gradtensor_data/PVP_phantom/scans/3tb/posB/OUTPUTS_future_fieldmap' ...
	);