addpath(genpath('../external/spm_read_nii'))
addpath(genpath('../external/spm_reslice'))
addpath('sh_basis')

if 0
	fieldmaps_to_gradtensor( ...
		'fieldmap_hz_0_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_0_Hz.nii', ...
		'fieldmap_hz_x_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_X_Hz.nii', ...
		'fieldmap_hz_y_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_Y_Hz.nii', ...
		'fieldmap_hz_z_file','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/INPUTS/B0_Z_Hz.nii', ...
		'sh_order',7, ...
		'symmetry','sym', ...
		'coord_geom','Philips_headfirst_supine', ...
		'image_radius',135, ...
		'out_dir','/nfs/masi/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/OUTPUTS' ...
		);
end


%create output dir
apply_approx_correction( ...	
    'Limg_file','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_future_fieldmap/OUTPUTS/L.nii.gz',   ...
    'refimg_file','/home/local/VANDERBILT/kanakap/gradtensor_data/10_29_2019_human_repositioned/3tb/posA/BLSA_estimates/BLSA_Lest_sig.nii', ...	
    'bval_file','/nfs/masi/kanakap/projects/LR/population_basis_study/data/Diffusion.bvals', ...
	'bvec_file','/nfs/masi/kanakap/projects/LR/population_basis_study/data/Diffusion.bvecs', ...
	'mask_path','/home/local/VANDERBILT/kanakap/gradtensor_data/10_29_2019_human_repositioned/3tb/posA/mask.nii',...
	'out_name','Lest',...
	'out_dir','/home/local/VANDERBILT/kanakap/gradtensor_data/10_29_2019_human_repositioned/3tb/posA/BLSA_sm' ...
	);
