addpath(genpath('../external/spm_read_nii'))
addpath(genpath('../external/spm_reslice'))
addpath('sh_basis')

	fieldmaps_to_gradtensor( ...
		'fieldmap_hz_0_file','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_true_fieldmap/INPUTS/B0_0_Hz.nii', ...
		'fieldmap_hz_x_file','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_true_fieldmap/INPUTS/X_linear.nii', ...
		'fieldmap_hz_y_file','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_true_fieldmap/INPUTS/Y_linear.nii', ...
		'fieldmap_hz_z_file','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_true_fieldmap/INPUTS/Z_linear.nii', ...
		'sh_order',5, ...
		'symmetry','sym', ...
		'coord_geom','Philips_headfirst_supine', ...
		'image_radius',135, ...
		'out_dir','/home/local/VANDERBILT/kanakap/gradtensor_data/fieldmaps/3tb_true_fieldmap/OUTPUTS_linear/' ...
		);
