dwi_path = '/home/local/VANDERBILT/kanakap/MASIVAR_LR_input1/sub-cIIs00_ses-s1Bx1_acq-b1000n32r25x25x25peAPP_run-112_dwi.nii.gz';
gunzip(dwi_path);
dwi_path = '/home/local/VANDERBILT/kanakap/MASIVAR_LR_input1/sub-cIIs00_ses-s1Bx1_acq-b1000n32r25x25x25peAPP_run-112_dwi.nii';
flags = struct( ...
'mask',true, ...
'mean',false, ...
'interp',1, ...
'which',1, ...
'wrap',[0 0 0], ...
'prefix','r' ...
);
wm ='/home/local/VANDERBILT/kanakap/MASIVAR_LR_input1/wmseg_reg_skull_stripped.nii.gz';
gunzip(wm)
wm ='/home/local/VANDERBILT/kanakap/MASIVAR_LR_input1/wmseg_reg_skull_stripped.nii';
spm_reslice({dwi_path;wm},flags)
